In [266]:
import numpy as np
import math
import pandas as pd 

In [267]:
df1 = pd.read_csv("C:/Users/Alex/PycharmProjects/WAOS/matrix3.csv")
df2 = pd.read_csv("C:/Users/Alex/PycharmProjects/WAOS/new_df2_v3.csv")
df3 = pd.read_csv("C:/Users/Alex/PycharmProjects/WAOS/new_df3_v2.csv")
df4 = pd.read_csv("C:/Users/Alex/PycharmProjects/WAOS/new_df4.csv")

In [268]:
df1.Singers = (df1.Singers.str.split(", ")).apply(set)

In [269]:
df1.loc[df1.Duration % 0.25 != 0, "Duration"] = df1[df1.Duration % 0.25 != 0].Duration.apply(lambda x: math.ceil(x*4)/4)

In [281]:
df1.Director = df1.Director.str.strip()

In [282]:
rehearsal_leads = df1.Director.unique()

In [284]:


rehearsals = {}
for rehearsal_lead in rehearsal_leads:
    to_rehearse = df1[df1.Director == rehearsal_lead]
    full_slots = to_rehearse[(to_rehearse.Duration % 1 == 0) & (to_rehearse.Duration > 0)]
    partial_slots = to_rehearse[to_rehearse.Duration % 1 != 0]
    rehearsals[rehearsal_lead] = {
        'full_slots': full_slots,
        'partial_slots': partial_slots
    }

    
    
    
    

In [285]:
rehearsals['MD']['full_slots']

Song  Duration Director  \
9                                       Hello Singing       1.0       MD   
29                           KONY Solo Dancer Singing       1.0       MD   
38                When I Grow Up inc Soloists Singing       1.0       MD   
39          Welcome to Wonderland All Singers Singing       1.0       MD   
40  Welcome to Wonderland Soloists Central Solos O...       1.0       MD   
44            On the Highway of Love Soloists Singing       1.0       MD   

                                              Singers  
9   {Holly Thompson, Kiah Whitehead, Laura Boswell...  
29  {Holly Thompson, Evan Huntley-Robertson, Steph...  
38  {Colin Bousfield, Phoebe Ponsford, Sophie Coad...  
39  {Eveey Ruth, Katharine Mann, Graham Broad, Son...  
40  {Graham Broad, Sonia Huntley-Robertson, Joey C...  
44  {Ellen da Costa, Emma Culley, Evan Huntley-Rob...

In [286]:
rehearsals['MD']['partial_slots']

Song  Duration Director  \
7                                  Freak Flag Singing      0.50       MD   
11                    When He Sees Me Backing Singing      0.50       MD   
13                Hard to be the Bard Backing Singing      0.50       MD   
16                         School Song Chorus Singing      0.75       MD   
17                         School Song Dancer Singing      0.25       MD   
19                        Why Cause I'm A Guy Singing      0.50       MD   
20                            Candy Store All Singing      0.50       MD   
23  Michael in the Bathroom Chorus Singing and Blo...      0.75       MD   
24                            Big Spender All Singing      0.50       MD   
25             On the Highway of Love Backing Singing      0.25       MD   
30                                KONY Chorus Singing      0.25       MD   
36                      Coffee Break no Solos Singing      0.75       MD   
37              Something's Coming Unison All Singing      0.75       MD   
43                Meet the Plastics Trio Only Singing      0.50       MD   
48                  Hard Knock Life Selected Soloists      0.25       MD   
50                   Freak Flag Three Piggies Singing      0.50       MD   
51                     Freak Flag Minor Solos Singing      0.25       MD   
52                               When I Drive Singing      0.50       MD   
53                                   Gun Song Singing      0.75       MD   
54                Graham and Nick Beetlejuice Singing      0.50       MD   

                                              Singers  
7   {Colin Bousfield, Holly Thompson, Dave Pound, ...  
11  {Sonia Huntley-Robertson, Laura Boswell, Heath...  
13  {Holly Thompson, Kiah Whitehead, Laura Boswell...  
16  {Tim Beasley, Joey Chan, Bertie Chatfield, San...  
17  {Holly Thompson, Evan Huntley-Robertson, Sharo...  
19  {Colin Bousfield, Patrick Coad, Dave Pound, Gr...  
20  {Lexi Dowle, Heather Bokota, Philippa Wilding,...  
23  {Colin Bousfield, Dave Pound, Graham Broad, Ph...  
24  {Patrick Coad, Holly Thompson, Eveey Ruth, Gra...  
25  {Patrick Coad, Eveey Ruth, Holly Thompson, Gra...  
30  {Patrick Coad, Eveey Ruth, Tim Beasley, Ellen ...  
36  {Eveey Ruth, Tim Beasley, Ellen McDermott, Ber...  
37  {Holly Thompson, Graham Broad, Kiah Whitehead,...  
43     {Ellen da Costa, Kelly Brewer, Kiah Whitehead}  
48      {Eveey Ruth, Laura Boswell, Lucy Ella-Foster}  
50  {Laura Boswell, Sanchez Simpson, Sonia Huntley...  
51     {Emma Morris, Ellen McDermott, Lynda Lawrence}  
52                    {Nick Reigate, Sanchez Simpson}  
53  {Evan Huntley-Robertson, Sanchez Simpson, Lexi...  
54                       {Nick Reigate, Graham Broad}

In [287]:
rehearsals.keys()

dict_keys(['Director', 'Choreo', 'MD'])

In [315]:
rehearsals.keys()

dict_keys(['Director', 'Choreo', 'MD'])

In [360]:
rehearsals[rehearsal_lead]["full_slots"][["Song", "Duration", "Singers"]]

Song  Duration  \
9                                       Hello Singing       1.0   
29                           KONY Solo Dancer Singing       1.0   
38                When I Grow Up inc Soloists Singing       1.0   
39          Welcome to Wonderland All Singers Singing       1.0   
40  Welcome to Wonderland Soloists Central Solos O...       1.0   
44            On the Highway of Love Soloists Singing       1.0   

                                              Singers  
9   {Holly Thompson, Kiah Whitehead, Laura Boswell...  
29  {Holly Thompson, Evan Huntley-Robertson, Steph...  
38  {Colin Bousfield, Phoebe Ponsford, Sophie Coad...  
39  {Eveey Ruth, Katharine Mann, Graham Broad, Son...  
40  {Graham Broad, Sonia Huntley-Robertson, Joey C...  
44  {Ellen da Costa, Emma Culley, Evan Huntley-Rob...

In [423]:

def make_solo_set(song_name):
    return {song_name}


song_pairings = {}
#for rehearsal_lead in ['Director']:
for rehearsal_lead in rehearsals:
    song_pairings[rehearsal_lead] = {}
    song_pairings[rehearsal_lead]['full_slots'] = rehearsals[rehearsal_lead]["full_slots"][["Song", "Duration", "Singers"]].rename(columns={
        'Song': 'set',
        'Duration': 'duration',
        'Singers': 'cast'
    })
    #song_pairings[rehearsal_lead]['full_slots'].loc[:, 'set'] = song_pairings[rehearsal_lead]['full_slots'].loc[:, 'set'].apply(make_solo_set)

    partial_slots = rehearsals[rehearsal_lead]["partial_slots"].copy()
    partial_slots['cast_size'] = partial_slots.Singers.apply(len)
    partial_slots = partial_slots.sort_values(by='cast_size', ascending=False).reset_index(drop=True)
    overlap_array = np.ones((len(partial_slots), len(partial_slots)))
    for i in range(len(partial_slots)):
        set_i = partial_slots.loc[i, "Singers"]
        
        for j in range(len(partial_slots)):
            if i == j:
                overlap_array[i,j] = -1
            else:
                set_j = partial_slots.loc[j, "Singers"]
                overlap_array[i,j] = len(set_i & set_j)/len(set_i | set_j)
    
    overlap_df = pd.DataFrame(overlap_array)    

    paired_songs = []
    paired_song_durations = []
    paired_song_full_cast = []
    unpaired_songs = []
    unpaired_song_durations = []
    unpaired_song_full_cast = []

    for song_index in partial_slots.sort_values(by="Duration", ascending=False).index:
        song_name = partial_slots.loc[song_index, "Song"]
        duration = partial_slots.loc[song_index, "Duration"]
        duo = True
        complementary_durations = [x for x in partial_slots.Duration.unique() if (x + duration) % 1 == 0]
        if not complementary_durations:
            print(f"No time match for {song_name}, recomputing with a trio")
            duo = False
            for i in partial_slots.Duration.unique():
                for j in partial_slots.Duration.unique():
                    if (i + j + duration) % 1 == 0:
                        if {i,j} not in complementary_durations:
                            complementary_durations.append({i,j})
            
            if not complementary_durations:
                print(f"No time match for {song_name}, recomputing with a quartet")

                for i in partial_slots.Duration.unique():
                    for j in partial_slots.Duration.unique():
                        for k in partial_slots.Duration.unique():
                            if (i + j + k + duration) % 1 == 0:
                                if {i,j,k} not in complementary_durations:
                                    complementary_durations.append({i,j,k})
                
                if not complementary_durations:
                    print(f"No time match for {song_name}, added to bin")
                    unpaired_songs.append(song_name)
                    unpaired_song_durations.append(duration)
                    unpaired_song_full_cast.append(partial_slots.loc[song_index, "Singers"])
        
        if complementary_durations:
            for complementary_duration in complementary_durations:
                song_set = {song_name}
                full_duration = duration
                singers = partial_slots.loc[song_index, "Singers"]
                if duo == True:
                    complementary_duration = [complementary_duration]
                for slot_size in complementary_duration:
                    possible_songs = partial_slots[partial_slots.Duration == slot_size].index
                    best_choice = overlap_df.loc[possible_songs, song_index].idxmax()
                    song_set.add(partial_slots.loc[best_choice, "Song"])
                    full_duration += slot_size
                    singers = singers | partial_slots.loc[best_choice, "Singers"]

                if song_set not in paired_songs:

                    paired_songs.append(song_set)
                    paired_song_durations.append(full_duration)
                    paired_song_full_cast.append(singers)
    
    if unpaired_songs:
        song_pairings[rehearsal_lead]['unpaired'] = pd.DataFrame.from_dict({
            'set': unpaired_songs,
            'duration': unpaired_song_durations,
            'cast': unpaired_song_full_cast,
        })

    song_pairings[rehearsal_lead]['paired']=pd.DataFrame.from_dict({
        'set': paired_songs,
        'duration': paired_song_durations,
        'cast': paired_song_full_cast
    })



No time match for Opening Night Blocking, recomputing with a trio
No time match for Goodbye Blocking, recomputing with a trio
No time match for Hard to be the Bard Blocking, recomputing with a trio
No time match for Why Cause I'm A Guy Blocking, recomputing with a trio
No time match for Big Spender All Blocking, recomputing with a trio
No time match for When He Sees Me Blocking, recomputing with a trio
No time match for Meet the Plastics All Choreo, recomputing with a trio
No time match for Meet the Plastics Trio Only Choreo, recomputing with a trio


In [424]:
song_pairings['Director']['full_slots']

set  duration  \
5                     Finale B Blocking       1.0   
27  On the Highway of Love All Blocking       1.0   
33          Something's Coming Blocking       1.0   
34              When I Grow Up Blocking       1.0   
55                When I Drive Blocking       1.0   
56                    Gun Song Blocking       1.0   

                                                 cast  
5   {Colin Bousfield, Holly Thompson, Dave Pound, ...  
27  {Patrick Coad, Eveey Ruth, Holly Thompson, Eva...  
33  {Holly Thompson, Graham Broad, Kiah Whitehead,...  
34  {Colin Bousfield, Phoebe Ponsford, Sophie Coad...  
55                    {Nick Reigate, Sanchez Simpson}  
56  {Evan Huntley-Robertson, Sanchez Simpson, Lexi...

In [430]:
song_pairings['Director']['paired'].to_csv('ex.csv')

In [426]:
song_pairings['Choreo']['full_slots']

set  duration  \
3                           TWBDT Choreo       3.0   
8                      Freak Flag Choreo       3.0   
10                          Hello Choreo       1.0   
15                   School Song Dancing       4.0   
18        Nowadays Hot Honey Rag Dancing       4.0   
22                    Candy Store Choreo       2.0   
28                          KONY Dancing       4.0   
35          Welcome to Wonderland Choreo       3.0   
41  Footloose Dancing and Backing Shouts       4.0   
42                  Good Morning Dancing       4.0   
49             I'm Not That Girl Dancing       4.0   

                                                 cast  
3   {Colin Bousfield, Holly Thompson, Dave Pound, ...  
8   {Colin Bousfield, Holly Thompson, Dave Pound, ...  
10  {Holly Thompson, Kiah Whitehead, Laura Boswell...  
15  {Holly Thompson, Evan Huntley-Robertson, Sharo...  
18  {Sharon Forsyth, Aimee Burton, Hannah Dare, Ph...  
22  {Lexi Dowle, Heather Bokota, Philippa Wilding,...  
28  {Holly Thompson, Evan Huntley-Robertson, Steph...  
35  {Eveey Ruth, Katharine Mann, Graham Broad, Son...  
41  {Holly Thompson, Evan Huntley-Robertson, Hanna...  
42  {Evan Huntley-Robertson, Ellie Morrow, Hannah ...  
49  {Lucy Ella-Foster, Ellie Morrow, Hannah Dare, ...

In [374]:
df1

Song  Duration  Director  \
0                              Opening Night Blocking      0.75  Director   
1                              Drink With Me Blocking      0.50  Director   
2                            Hard Knock Life Blocking      1.50  Director   
3                                        TWBDT Choreo      3.00    Choreo   
4                         Once We Were Kings Blocking      1.50  Director   
5                                   Finale B Blocking      1.00  Director   
6                                    Goodbye Blocking      0.75  Director   
7                                  Freak Flag Singing      0.50        MD   
8                                   Freak Flag Choreo      3.00    Choreo   
9                                       Hello Singing      1.00        MD   
10                                       Hello Choreo      1.00    Choreo   
11                    When He Sees Me Backing Singing      0.50        MD   
12                           When He Sees Me Blocking      0.75  Director   
13                Hard to be the Bard Backing Singing      0.50        MD   
14                       Hard to be the Bard Blocking      0.75  Director   
15                                School Song Dancing      4.00    Choreo   
16                         School Song Chorus Singing      0.75        MD   
17                         School Song Dancer Singing      0.25        MD   
18                     Nowadays Hot Honey Rag Dancing      4.00    Choreo   
19                        Why Cause I'm A Guy Singing      0.50        MD   
20                            Candy Store All Singing      0.50        MD   
21                       Why Cause I'm A Guy Blocking      0.75  Director   
22                                 Candy Store Choreo      2.00    Choreo   
23  Michael in the Bathroom Chorus Singing and Blo...      0.75        MD   
24                            Big Spender All Singing      0.50        MD   
25             On the Highway of Love Backing Singing      0.25        MD   
26                           Big Spender All Blocking      0.75  Director   
27                On the Highway of Love All Blocking      1.00  Director   
28                                       KONY Dancing      4.00    Choreo   
29                           KONY Solo Dancer Singing      1.00        MD   
30                                KONY Chorus Singing      0.25        MD   
31                               KONY Chorus Blocking      0.50  Director   
32                                Coffee Break Choreo      2.50    Choreo   
33                        Something's Coming Blocking      1.00  Director   
34                            When I Grow Up Blocking      1.00  Director   
35                       Welcome to Wonderland Choreo      3.00    Choreo   
36                      Coffee Break no Solos Singing      0.75        MD   
37              Something's Coming Unison All Singing      0.75        MD   
38                When I Grow Up inc Soloists Singing      1.00        MD   
39          Welcome to Wonderland All Singers Singing      1.00        MD   
40  Welcome to Wonderland Soloists Central Solos O...      1.00        MD   
41               Footloose Dancing and Backing Shouts      4.00    Choreo   
42                               Good Morning Dancing      4.00    Choreo   
43                Meet the Plastics Trio Only Singing      0.50        MD   
44            On the Highway of Love Soloists Singing      1.00        MD   
45           On the Highway of Love Soloists Blocking      0.00  Director   
46                 Meet the Plastics Trio Only Choreo      0.75    Choreo   
47                       Meet the Plastics All Choreo      0.75    Choreo   
48                  Hard Knock Life Selected Soloists      0.25        MD   
49                          I'm Not That Girl Dancing      4.00    Choreo   
50                   Freak Flag Three Piggies Singing      0.50        MD   
51                     Freak Flag Minor Solos

In [348]:
df1

Song  Duration  Director  \
0                              Opening Night Blocking      0.75  Director   
1                              Drink With Me Blocking      0.50  Director   
2                            Hard Knock Life Blocking      1.50  Director   
3                                        TWBDT Choreo      3.00    Choreo   
4                         Once We Were Kings Blocking      1.50  Director   
5                                   Finale B Blocking      1.00  Director   
6                                    Goodbye Blocking      0.75  Director   
7                                  Freak Flag Singing      0.50        MD   
8                                   Freak Flag Choreo      3.00    Choreo   
9                                       Hello Singing      1.00        MD   
10                                       Hello Choreo      1.00    Choreo   
11                    When He Sees Me Backing Singing      0.50        MD   
12                           When He Sees Me Blocking      0.75  Director   
13                Hard to be the Bard Backing Singing      0.50        MD   
14                       Hard to be the Bard Blocking      0.75  Director   
15                                School Song Dancing      4.00    Choreo   
16                         School Song Chorus Singing      0.75        MD   
17                         School Song Dancer Singing      0.25        MD   
18                     Nowadays Hot Honey Rag Dancing      4.00    Choreo   
19                        Why Cause I'm A Guy Singing      0.50        MD   
20                            Candy Store All Singing      0.50        MD   
21                       Why Cause I'm A Guy Blocking      0.75  Director   
22                                 Candy Store Choreo      2.00    Choreo   
23  Michael in the Bathroom Chorus Singing and Blo...      0.75        MD   
24                            Big Spender All Singing      0.50        MD   
25             On the Highway of Love Backing Singing      0.25        MD   
26                           Big Spender All Blocking      0.75  Director   
27                On the Highway of Love All Blocking      1.00  Director   
28                                       KONY Dancing      4.00    Choreo   
29                           KONY Solo Dancer Singing      1.00        MD   
30                                KONY Chorus Singing      0.25        MD   
31                               KONY Chorus Blocking      0.50  Director   
32                                Coffee Break Choreo      2.50    Choreo   
33                        Something's Coming Blocking      1.00  Director   
34                            When I Grow Up Blocking      1.00  Director   
35                       Welcome to Wonderland Choreo      3.00    Choreo   
36                      Coffee Break no Solos Singing      0.75        MD   
37              Something's Coming Unison All Singing      0.75        MD   
38                When I Grow Up inc Soloists Singing      1.00        MD   
39          Welcome to Wonderland All Singers Singing      1.00        MD   
40  Welcome to Wonderland Soloists Central Solos O...      1.00        MD   
41               Footloose Dancing and Backing Shouts      4.00    Choreo   
42                               Good Morning Dancing      4.00    Choreo   
43                Meet the Plastics Trio Only Singing      0.50        MD   
44            On the Highway of Love Soloists Singing      1.00        MD   
45           On the Highway of Love Soloists Blocking      0.00  Director   
46                 Meet the Plastics Trio Only Choreo      0.75    Choreo   
47                       Meet the Plastics All Choreo      0.75    Choreo   
48                  Hard Knock Life Selected Soloists      0.25        MD   
49                          I'm Not That Girl Dancing      4.00    Choreo   
50                   Freak Flag Three Piggies Singing      0.50        MD   
51                     Freak Flag Minor Solos

In [245]:
songs_left_to_group = list(partial_slots.sort_values(by="Duration", ascending=False).index)

In [249]:
songs_left = partial_slots.loc[partial_slots.index.isin(songs_left_to_group)]
songs_left[songs_left.Duration == 0.25]

Song  Duration Director  \
2                      KONY Chorus Singing      0.25       MD   
8   On the Highway of Love Backing Singing      0.25       MD   
11              School Song Dancer Singing      0.25       MD   
15       Hard Knock Life Selected Soloists      0.25       MD   
17          Freak Flag Minor Solos Singing      0.25       MD   

                                              Singers  cast_size  
2   {Patrick Coad, Eveey Ruth, Tim Beasley, Ellen ...         13  
8   {Patrick Coad, Eveey Ruth, Holly Thompson, Gra...         10  
11  {Holly Thompson, Evan Huntley-Robertson, Sharo...          8  
15      {Eveey Ruth, Laura Boswell, Lucy Ella-Foster}          3  
17     {Emma Morris, Ellen McDermott, Lynda Lawrence}          3

In [243]:
partial_slots.loc[song_index, "Duration"]

0.75

In [241]:
[(i, j) for (i in partial_slots.Duration.unique()) and (j in partial_slots.Duration.unique()) if (i + j + partial_slots.loc[song_index, "Duration"]) % 1 == 0]

SyntaxError: expected 'else' after 'if' expression (2682638195.py, line 1)

In [236]:
song_index = 1
partial_slots.loc[song_index, "Duration"]

0.75

In [237]:
partial_slots.Duration.unique()

array([0.5 , 0.75, 0.25])

[0.25]

In [193]:
pd.DataFrame(overlap_array)

0         1         2         3         4         5         6   \
0  -1.000000  0.425532  0.276596  0.255319  0.234043  0.234043  0.234043   
1   0.425532 -1.000000  0.222222  0.185185  0.192308  0.148148  0.550000   
2   0.276596  0.222222 -1.000000  0.190476  0.846154  0.142857  0.200000   
3   0.255319  0.185185  0.190476 -1.000000  0.150000  0.210526  0.000000   
4   0.234043  0.192308  0.846154  0.150000 -1.000000  0.100000  0.157895   
5   0.234043  0.148148  0.142857  0.210526  0.100000 -1.000000  0.157895   
6   0.234043  0.550000  0.200000  0.000000  0.157895  0.157895 -1.000000   
7   0.212766  0.071429  0.150000  0.100000  0.105263  0.235294  0.105263   
8   0.212766  0.071429  0.150000  0.100000  0.105263  0.235294  0.105263   
9   0.191489  0.450000  0.100000  0.312500  0.111111  0.052632  0.000000   
10  0.170213  0.120000  0.235294  0.428571  0.187500  0.117647  0.000000   
11  0.170213  0.166667  0.000000  0.333333  0.000000  0.117647  0.000000   
12  0.148936  0.173913  0.176471  0.000000  0.200000  0.058824  0.285714   
13  0.085106  0.142857  0.133333  0.000000  0.153846  0.071429  0.153846   
14  0.063830  0.095238  0.066667  0.250000  0.076923  0.076923  0.000000   
15  0.063830  0.045455  0.142857  0.071429  0.166667  0.076923  0.000000   
16  0.063830  0.045455  0.066667  0.071429  0.076923  0.076923  0.076923   
17  0.063830  0.000000  0.142857  0.000000  0.166667  0.076923  0.000000   
18  0.042553  0.100000  0.071429  0.000000  0.083333  0.181818  0.181818   
19  0.042553  0.100000  0.071429  0.000000  0.083333  0.181818  0.181818   

          7         8         9         10        11        12        13  \
0   0.212766  0.212766  0.191489  0.170213  0.170213  0.148936  0.085106   
1   0.071429  0.071429  0.450000  0.120000  0.166667  0.173913  0.142857   
2   0.150000  0.150000  0.100000  0.235294  0.000000  0.176471  0.133333   
3   0.100000  0.100000  0.312500  0.428571  0.333333  0.000000  0.000000   
4   0.105263  0.105263  0.111111  0.187500  0.000000  0.200000  0.153846   
5   0.235294  0.235294  0.052632  0.117647  0.117647  0.058824  0.071429   
6   0.105263  0.105263  0.000000  0.000000  0.000000  0.285714  0.153846   
7  -1.000000  1.000000  0.000000  0.125000  0.058824  0.133333  0.000000   
8   1.000000 -1.000000  0.000000  0.125000  0.058824  0.133333  0.000000   
9   0.000000  0.000000 -1.000000  0.214286  0.307692  0.000000  0.083333   
10  0.125000  0.125000  0.214286 -1.000000  0.000000  0.000000  0.000000   
11  0.058824  0.058824  0.307692  0.000000 -1.000000  0.000000  0.090909   
12  0.133333  0.133333  0.000000  0.000000  0.000000 -1.000000  0.222222   
13  0.000000  0.000000  0.083333  0.000000  0.090909  0.222222 -1.000000   
14  0.000000  0.000000  0.200000  0.100000  0.100000  0.000000  0.000000   
15  0.083333  0.083333  0.090909  0.100000  0.100000  0.000000  0.000000   
16  0.083333  0.083333  0.000000  0.222222  0.000000  0.111111  0.166667   
17  0.083333  0.083333  0.000000  0.000000  0.000000  0.111111  0.000000   
18  0.000000  0.000000  0.000000  0.000000  0.000000  0.125000  0.200000   
19  0.090909  0.090909  0.000000  0.000000  0.000000  0.000000  0.000000   

          14        15        16        17        18        19  
0   0.063830  0.063830  0.063830  0.063830  0.042553  0.042553  
1   0.095238  0.045455  0.045455  0.000000  0.100000  0.100000  
2   0.066667  0.142857  0.066667  0.142857  0.071429  0.071429  
3   0.250000  0.071429  0.071429  0.000000  0.000000  0.000000  
4   0.076923  0.166667  0.076923  0.166667  0.083333  0.083333  
5   0.076923  0.076923  0.076923  0.076923  0.181818  0.181818  
6   0.000000  0.000000  0.076923  0.000000  0.181818  0.181818  
7   0.000000  0.083333  0.083333  0.083333  0.000000  0.090909  
8   0.000000  0.083333  0.083333  0.083333  0.000000  0.090909  
9   0.200000  0.090909  0.000000  0.000000  0.000000  0.000000  
10  0.100000  0.100000  0.222222  0.000000  0.000000  0.000000  
11  0.100000  0.100000  0.000000  0.

In [192]:
0.75 % 0.5

0.25

In [156]:
len(set_i & set_j)

2

In [157]:
len(set_i | set_j)

2

In [149]:
partial_slots

Song  Duration Director  \
0                                  Freak Flag Singing      0.50       MD   
1   Michael in the Bathroom Chorus Singing and Blo...      0.75       MD   
2                                 KONY Chorus Singing      0.25       MD   
3                 Hard to be the Bard Backing Singing      0.40       MD   
4                       Coffee Break no Solos Singing      0.75       MD   
5               Something's Coming Unison All Singing      0.75       MD   
6                         Why Cause I'm A Guy Singing      0.50       MD   
7                             Big Spender All Singing      0.50       MD   
8              On the Highway of Love Backing Singing      0.25       MD   
9                             Candy Store All Singing      0.50       MD   
10                    When He Sees Me Backing Singing      0.50       MD   
11                         School Song Dancer Singing      0.25       MD   
12                         School Song Chorus Singing      0.75       MD   
13                                   Gun Song Singing      0.75       MD   
14                Meet the Plastics Trio Only Singing      0.50       MD   
15                  Hard Knock Life Selected Soloists      0.20       MD   
16                   Freak Flag Three Piggies Singing      0.50       MD   
17                     Freak Flag Minor Solos Singing      0.25       MD   
18                               When I Drive Singing      0.50       MD   
19                Graham and Nick Beetlejuice Singing      0.50       MD   

                                              Singers  cast_size  
0   {Colin Bousfield, Holly Thompson, Dave Pound, ...         47  
1   {Colin Bousfield, Dave Pound, Graham Broad, Ph...         20  
2   {Patrick Coad, Eveey Ruth, Tim Beasley, Ellen ...         13  
3   {Holly Thompson, Kiah Whitehead, Laura Boswell...         12  
4   {Eveey Ruth, Tim Beasley, Ellen McDermott, Ber...         11  
5   {Holly Thompson, Graham Broad, Kiah Whitehead,...         11  
6   {Colin Bousfield, Patrick Coad, Dave Pound, Gr...         11  
7   {Patrick Coad, Holly Thompson, Eveey Ruth, Gra...         10  
8   {Patrick Coad, Eveey Ruth, Holly Thompson, Gra...         10  
9   {Lexi Dowle, Heather Bokota, Philippa Wilding,...          9  
10  {Sonia Huntley-Robertson, Laura Boswell, Heath...          8  
11  {Holly Thompson, Evan Huntley-Robertson, Sharo...          8  
12  {Tim Beasley, Joey Chan, Bertie Chatfield, San...          7  
13  {Evan Huntley-Robertson, Sanchez Simpson, Lexi...          4  
14     {Ellen da Costa, Kelly Brewer, Kiah Whitehead}          3  
15      {Eveey Ruth, Laura Boswell, Lucy Ella-Foster}          3  
16  {Laura Boswell, Sanchez Simpson, Sonia Huntley...          3  
17     {Emma Morris, Ellen McDermott, Lynda Lawrence}          3  
18                    {Nick Reigate, Sanchez Simpson}          2  
19                       {Nick Reigate, Graham Broad}          2

In [151]:
print(np.ones((len(partial_slots), len(partial_slots))))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.